### ISSUE TITLE
Usage with Docker-Compose

### ISSUE THREAD

**Issue by qMalte** [victronenergy/venus-docker#15]
Hello,

I would like to use this Docker image using Docker Compose.

When I start the container using demo data it works fine, but when I use the script: start_services.sh as entrypoint the container restarts every few seconds.

Can someone tell me how to make the container run permanently?

My DockerCompose configuration looks like this:

`version: "3"

services:
  victron:
    image: myship/venus
    ports:
      - 3000:3000
      - 9001:9001
      - 1883:1883
      - 8080:80
    entrypoint: /root/start_services.sh
    restart: unless-stopped`

I am glad about your answers

Many greetings
Malte

**Comment by LeMaBa** [comment]
Hey @qMalte,

i have just started to use the docker image. Not sure if the issue is still pending, but i think your problem lies in the entrypoint you are using. 
I tried to use the Image with Portainer and searched in the run.sh for the Docker Command and found:
`docker run -d --rm -p $WSPORT:9001 -p $MQTTPORT:1883 -p $DBUSTCPPORT:3000 -p $APP_PORT:80 mqtt /root/run_with_simulation.sh z` 

So the run.sh adds the command `/root/run_with_simulation.sh z` to start the appilcation within the container with the simulation parameter `z` 

so to run the docker compose try to add instead of the entrypoint:
`command: /root/run_with_simulation.sh z`

Many greeting
